// <auto-generated />
using System;
using CodeSphere.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSphere.DataAccess.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118123849_AddDsaQuestionDefinition")]
    partial class AddDsaQuestionDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSphere.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DsaQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DsaQuestionId")
                        .IsUnique();

                    b.ToTable("DsaQuestionDefinitions");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionDefinitionParameteres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DsaQuestionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParameterOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DsaQuestionDefinitionId");

                    b.ToTable("DsaQuestionDefinitionParameteres");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionTestCases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DsaQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DsaQuestionId");

                    b.ToTable("DsaQuestionTestCases");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DsaQuestions");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaTopicQuestions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DsaQuestionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DsaTopicsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DsaQuestionsId");

                    b.HasIndex("DsaTopicsId");

                    b.ToTable("DsaTopicQuestions");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaTopics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("TopicLevel")
                        .HasColumnType("integer");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DsaTopics");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "User",
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Admin",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Videos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionDefinition", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.DsaQuestions", "DsaQuestion")
                        .WithOne("Definition")
                        .HasForeignKey("CodeSphere.Domain.Entities.DsaQuestionDefinition", "DsaQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsaQuestion");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionDefinitionParameteres", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.DsaQuestionDefinition", "DsaQuestionDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("DsaQuestionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsaQuestionDefinition");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionTestCases", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.DsaQuestions", "DsaQuestion")
                        .WithMany("TestCases")
                        .HasForeignKey("DsaQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsaQuestion");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaTopicQuestions", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.DsaQuestions", "DsaQuestions")
                        .WithMany("TopicQuestions")
                        .HasForeignKey("DsaQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSphere.Domain.Entities.DsaTopics", "DsaTopics")
                        .WithMany("TopicQuestions")
                        .HasForeignKey("DsaTopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DsaQuestions");

                    b.Navigation("DsaTopics");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Topic", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.Course", "Course")
                        .WithMany("topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSphere.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Videos", b =>
                {
                    b.HasOne("CodeSphere.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Course", b =>
                {
                    b.Navigation("topics");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestionDefinition", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaQuestions", b =>
                {
                    b.Navigation("Definition");

                    b.Navigation("TestCases");

                    b.Navigation("TopicQuestions");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.DsaTopics", b =>
                {
                    b.Navigation("TopicQuestions");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CodeSphere.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
